<?php

use Illuminate\Support\Facades\File;

/**
 * Cross-implementation check between the browser crypto core and PHP's
 * ext-sodium.
 *
 * A round-trip test proves only that our encrypt and decrypt agree with each
 * other — they would agree just as happily while both being wrong about byte
 * order, parameter mapping or associated-data encoding. An independent
 * implementation is what catches that.
 *
 * The flow is deliberately two-sided:
 *
 *   - This test regenerates every vector with ext-sodium and asserts it matches
 *     the committed fixture, so PHP-side drift fails here.
 *   - resources/js/crypto/interop.test.ts reads the same fixture and asserts the
 *     TypeScript implementation reproduces it, so JS-side drift fails there.
 *
 * Changing the fixture therefore requires a deliberate, coordinated change on
 * both sides — which is the point.
 *
 * Regenerate with: VAULT_UPDATE_CRYPTO_FIXTURE=1 php artisan test --filter=interop
 */
function fixturePath(): string
{
    return base_path('tests/Fixtures/crypto-interop.json');
}

/**
 * Mirrors buildAad() in resources/js/crypto/aad.ts, implemented independently
 * so that an encoding mistake in one does not silently match the other.
 *
 * @param  array{context: string, subject: string, version: int}  $params
 */
function buildAad(array $params): string
{
    return implode("\0", [
        'vault.v1',
        $params['context'],
        strtolower($params['subject']),
        (string) $params['version'],
    ]);
}

/**
 * Decodes a fixed hex literal from a test vector.
 *
 * sodium_hex2bin throws on malformed input rather than returning false, and the
 * emptiness guard narrows the result to non-empty-string for the sodium
 * functions that require one.
 *
 * @return non-empty-string
 */
function decodeHex(string $hex): string
{
    $bytes = sodium_hex2bin($hex);

    if ($bytes === '') {
        throw new InvalidArgumentException("Test vector [{$hex}] decoded to an empty string.");
    }

    return $bytes;
}

/**
 * @return array{
 *     _comment: string,
 *     aad: array{params: array{context: string, subject: string, version: int}, bytes: string},
 *     xchacha20poly1305: array{key: string, nonce: string, aad: string, plaintext: string, body: string},
 *     blake2b256: array{input: string, digest: string},
 *     hkdf_sha256: array{ikm: string, salt: string, info: string, okm: string},
 *     argon2id: array{m: int, t: int, p: int, dkLen: int, password: string, salt: string, output: string},
 *     x25519: array{aliceSecret: string, alicePublic: string, bobSecret: string, bobPublic: string, shared: string},
 *     ed25519: array{seed: string, publicKey: string, message: string, signature: string}
 * }
 */
function generateVectors(): array
{
    $aadParams = [
        'context' => 'secret.payload',
        'subject' => '0192f3a1-4b2c-7d3e-8f90-a1b2c3d4e5f6',
        'version' => 1,
    ];

    $aad = buildAad($aadParams);

    $key = str_repeat("\x01", 32);
    $nonce = str_repeat("\x02", 24);
    $plaintext = '{"key":"AWS root — production","value":"hunter2 🔐"}';

    // sodium_hex2bin throws on malformed input rather than returning false,
    // which keeps these fixed literals honestly typed as strings.
    $aliceSecret = decodeHex('77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a');
    $bobSecret = decodeHex('5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb');
    $bobPublic = sodium_crypto_scalarmult_base($bobSecret);

    $signSeed = decodeHex('9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60');
    $signKeypair = sodium_crypto_sign_seed_keypair($signSeed);
    $signMessage = 'grant:0192f3a1-4b2c-7d3e-8f90-a1b2c3d4e5f6';

    $hkdfIkm = str_repeat("\x0b", 22);
    $hkdfSalt = decodeHex('000102030405060708090a0b0c');

    $blakeInput = 'vault fingerprint input';

    $password = 'correct horse battery staple';
    $argonSalt = str_repeat("\x07", 16);

    // Small parameters keep both suites fast. They validate the m/t/p mapping,
    // which is the thing that could differ between implementations; the
    // production cost is measured by npm run bench:argon2 (ADR-0003).
    $argon = ['m' => 64, 't' => 2, 'p' => 1, 'dkLen' => 64];

    return [
        '_comment' => 'Generated by tests/Feature/CryptoInteropTest.php using ext-sodium. Do not edit by hand.',
        'aad' => [
            'params' => $aadParams,
            'bytes' => bin2hex($aad),
        ],
        'xchacha20poly1305' => [
            'key' => bin2hex($key),
            'nonce' => bin2hex($nonce),
            'aad' => bin2hex($aad),
            'plaintext' => bin2hex($plaintext),
            'body' => bin2hex(
                sodium_crypto_aead_xchacha20poly1305_ietf_encrypt($plaintext, $aad, $nonce, $key)
            ),
        ],
        'blake2b256' => [
            'input' => bin2hex($blakeInput),
            'digest' => bin2hex(sodium_crypto_generichash($blakeInput, '', 32)),
        ],
        'hkdf_sha256' => [
            'ikm' => bin2hex($hkdfIkm),
            'salt' => bin2hex($hkdfSalt),
            'info' => 'vault:seal:v1',
            'okm' => bin2hex(hash_hkdf('sha256', $hkdfIkm, 32, 'vault:seal:v1', $hkdfSalt)),
        ],
        'argon2id' => [
            ...$argon,
            'password' => $password,
            'salt' => bin2hex($argonSalt),
            'output' => bin2hex(sodium_crypto_pwhash(
                $argon['dkLen'],
                $password,
                $argonSalt,
                $argon['t'],
                $argon['m'] * 1024,
                SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13,
            )),
        ],
        'x25519' => [
            'aliceSecret' => bin2hex($aliceSecret),
            'alicePublic' => bin2hex(sodium_crypto_scalarmult_base($aliceSecret)),
            'bobSecret' => bin2hex($bobSecret),
            'bobPublic' => bin2hex($bobPublic),
            'shared' => bin2hex(sodium_crypto_scalarmult($aliceSecret, $bobPublic)),
        ],
        'ed25519' => [
            'seed' => bin2hex($signSeed),
            'publicKey' => bin2hex(sodium_crypto_sign_publickey($signKeypair)),
            'message' => bin2hex($signMessage),
            'signature' => bin2hex(sodium_crypto_sign_detached(
                $signMessage,
                sodium_crypto_sign_secretkey($signKeypair)
            )),
        ],
    ];
}

it('has ext-sodium available', function () {
    expect(extension_loaded('sodium'))->toBeTrue();
});

it('reproduces the committed interop fixture', function () {
    $vectors = generateVectors();

    // getenv rather than env(): this is a developer-run toggle, and Larastan
    // rightly objects to env() outside the config directory.
    if (getenv('VAULT_UPDATE_CRYPTO_FIXTURE')) {
        File::ensureDirectoryExists(dirname(fixturePath()));
        File::put(
            fixturePath(),
            json_encode($vectors, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)."\n"
        );
    }

    expect(File::exists(fixturePath()))->toBeTrue(
        'Fixture missing. Regenerate with VAULT_UPDATE_CRYPTO_FIXTURE=1 php artisan test --filter=interop'
    );

    // Divergence means PHP now produces different bytes than when the fixture
    // was written: a library upgrade, a parameter change, or a mistake.
    expect(generateVectors())->toEqual(File::json(fixturePath()));
});

it('decrypts what the documented envelope layout describes', function () {
    $aead = generateVectors()['xchacha20poly1305'];

    $plaintext = sodium_crypto_aead_xchacha20poly1305_ietf_decrypt(
        sodium_hex2bin($aead['body']),
        sodium_hex2bin($aead['aad']),
        sodium_hex2bin($aead['nonce']),
        sodium_hex2bin($aead['key']),
    );

    expect($plaintext)->toBe(sodium_hex2bin($aead['plaintext']));
});

it('rejects the envelope body when the associated data differs', function () {
    $aead = generateVectors()['xchacha20poly1305'];

    // The AAD binding (SR4), verified from the other side of the boundary.
    $rebound = buildAad([
        'context' => 'secret.payload',
        'subject' => '0192f3a1-4b2c-7d3e-8f90-a1b2c3d4e5f7',
        'version' => 1,
    ]);

    expect(sodium_crypto_aead_xchacha20poly1305_ietf_decrypt(
        sodium_hex2bin($aead['body']),
        $rebound,
        sodium_hex2bin($aead['nonce']),
        sodium_hex2bin($aead['key']),
    ))->toBeFalse();
});
