<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Version history for secrets, and the retention policy that bounds it.
 *
 * **A version is its own encrypted item, not a copy of an old column.** The
 * client re-seals the outgoing plaintext under a fresh Item Key, with associated
 * data bound to the context `secret.version.payload` and to this row's own UUID,
 * before it posts the replacement.
 *
 * The obvious cheaper design — have the server copy `secrets.payload_ct` into
 * this table on update — is the one thing that must not happen. Copied bytes
 * carry their original associated data, which binds them to `secret.payload` at
 * the secret's UUID: byte-for-byte the same binding the live column has. A
 * server holding both could then write any archived version back over the live
 * row and every client would verify it happily. That is a silent rollback of a
 * rotated credential to the one that leaked — the exact attack that adding
 * history creates, and re-sealing under a distinct context and subject is what
 * closes it (SR4).
 *
 * It costs an extra payload on the wire per edit, and it means a secret whose
 * ciphertext no longer verifies cannot be edited at all: an edit must archive
 * what it replaces, and a client cannot archive what it cannot read. Deleting
 * and re-adding is the way out, and it keeps the unreadable row rather than
 * overwriting the evidence.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('secret_versions', function (Blueprint $table) {
            $table->id();

            /*
             | Generated by the client, and load-bearing rather than cosmetic:
             | it is the AAD subject the archived payload is sealed against. A
             | server-generated identifier would arrive after the sealing that
             | needed it.
             */
            $table->uuid('uuid')->unique();

            $table->foreignId('secret_id')->constrained()->cascadeOnDelete();

            /*
             | Which `secrets.current_version` this payload was live at. Unique
             | with the secret, so a client that replayed an archive — or two
             | that raced past the optimistic-concurrency guard — collides here
             | rather than writing a second, contradictory history for one
             | number.
             */
            $table->unsignedInteger('version');

            $table->text('payload_ct');
            $table->text('wrapped_item_key');
            $table->unsignedSmallInteger('payload_version')->default(1);

            /*
             | Who made the edit that produced this archive. `nullOnDelete`
             | rather than the audit log's bare UUID: this is display metadata
             | on a mutable row, not a link in a hash chain, so a closed account
             | leaving a null behind costs nothing.
             */
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();

            /*
             | `updated_at` exists for one writer only: a Vault Key rotation
             | re-wraps every version's Item Key along with every live item's.
             | A version's *content* never changes — the model refuses that —
             | but the key that opens it does, and a row whose wrapping moved
             | while its timestamp did not would be a quietly misleading record.
             */
            $table->timestamps();

            $table->unique(['secret_id', 'version']);
            // Newest-first for one secret, which is the only way this is read.
            $table->index(['secret_id', 'created_at']);
        });

        Schema::table('vaults', function (Blueprint $table) {
            /*
             | Retention, per vault, null meaning "whatever config/vault.php
             | says". Stored rather than derived because the sweep runs without
             | a user and has to know what this vault asked for.
             |
             | Both are plaintext, and they leak: an observer learns that one
             | vault keeps no history and another keeps five years of it, which
             | is a weak signal about how the vault is used. It is recorded in
             | docs/02-threat-model.md under accepted leakage rather than
             | encrypted, because the server is the thing that has to enforce
             | it — a retention policy only the client could read would be a
             | retention policy nothing enforces.
             |
             | Zero versions is the honest way to turn history off for a vault
             | whose contents are rotated *because* they leak.
             */
            $table->unsignedSmallInteger('history_max_versions')->nullable();
            $table->unsignedSmallInteger('history_max_age_days')->nullable();
        });
    }

    public function down(): void
    {
        Schema::table('vaults', function (Blueprint $table) {
            $table->dropColumn(['history_max_versions', 'history_max_age_days']);
        });

        Schema::dropIfExists('secret_versions');
    }
};
