<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Vaults, their membership, and the two levels of content beneath them.
 *
 * The shape is the 2017 application's — vaults hold lockboxes hold secrets —
 * and almost every column is different. What was plaintext there (`vaults.name`,
 * `secrets.key`, `files.original_name`) is inside `payload_ct` here. What
 * remains in the clear is written down with its reason in
 * docs/04-data-model.md, and nothing that remains identifies a secret's
 * contents, type or purpose.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('vaults', function (Blueprint $table) {
            $table->id();

            /*
             | Generated by the client, because the payload is encrypted with
             | associated data bound to this identifier before the row exists.
             | The server checks the version and uniqueness and nothing else.
             */
            $table->uuid('uuid')->unique();

            $table->foreignId('owner_id')->constrained('users')->cascadeOnDelete();

            // {name, description}. The name is encrypted — the single biggest
            // change from 2017, where vaults.name was a plaintext column.
            $table->text('payload_ct');
            $table->text('wrapped_item_key');
            $table->unsignedSmallInteger('payload_version')->default(1);

            /*
             | Advances on every rotation. A membership is only usable when its
             | epoch matches, which is what makes a partially-applied re-key
             | impossible to mistake for a complete one (Phase 5).
             */
            $table->unsignedInteger('key_epoch')->default(1);
            $table->timestamp('rekey_required_at')->nullable();

            $table->timestamps();
            $table->softDeletes();
        });

        /*
         | Replaces the 2017 `user_vault` pivot and its `read_only` boolean.
         |
         | `role` is enforced by the server for writes. It is not, and cannot be,
         | enforced cryptographically for reads: anyone holding the Vault Key can
         | decrypt. See docs/01-brief-and-decisions.md.
         */
        Schema::create('vault_memberships', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique();

            $table->foreignId('vault_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->string('role');

            // The Vault Key sealed to this member's X25519 public key. The AAD
            // binds it to this membership, so the server cannot move one
            // member's wrapped key onto another's row.
            $table->text('wrapped_vault_key');
            $table->unsignedInteger('key_epoch')->default(1);

            $table->foreignId('granted_by')->nullable()->constrained('users')->nullOnDelete();

            /*
             | Phase 5 fills these in and requires them. Nullable now so that
             | adding signed grants is a change to the write path rather than a
             | migration of a populated table.
             |
             | `grant_payload` stores the exact bytes that were signed, so a
             | future change to canonicalisation cannot invalidate signatures
             | already issued.
             */
            $table->text('grant_signature')->nullable();
            $table->json('grant_payload')->nullable();

            $table->timestamp('accepted_at')->nullable();
            $table->timestamp('revoked_at')->nullable();
            $table->timestamps();

            $table->unique(['vault_id', 'user_id']);
            // The authorisation check on every single request.
            $table->index(['user_id', 'vault_id']);
        });

        Schema::create('lockboxes', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique();
            $table->foreignId('vault_id')->constrained()->cascadeOnDelete();

            // {name, description, notes}
            $table->text('payload_ct');
            $table->text('wrapped_item_key');
            $table->unsignedSmallInteger('payload_version')->default(1);

            // Plaintext: it leaks ordering only, and sorting has to work before
            // anything is decrypted.
            $table->integer('sort_order')->default(0);

            $table->timestamps();
            $table->softDeletes();

            $table->index(['vault_id', 'sort_order']);
        });

        Schema::create('secrets', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique();
            $table->foreignId('lockbox_id')->constrained()->cascadeOnDelete();

            /*
             | {type, key, value, notes, totp?, url?} — including the type.
             |
             | A `type` enum column would tell the server which rows are TOTP
             | seeds, which are SSH keys and which are notes: a targeting signal
             | for free. The 2017 `paranoid` flag moves in here too, as a
             | client-side UI hint. It was never a security control.
             */
            $table->text('payload_ct');
            $table->text('wrapped_item_key');
            $table->unsignedSmallInteger('payload_version')->default(1);

            /*
             | The 2017 lockbox-as-a-value feature, kept.
             |
             | Plaintext because the server enforces that both ends live in the
             | same vault, which requires seeing the edge. It leaks graph
             | structure that the foreign keys leak already.
             */
            $table->foreignId('linked_lockbox_id')->nullable()->constrained('lockboxes')->nullOnDelete();

            $table->integer('sort_order')->default(0);
            // Mirrors secret_versions, which arrives in Phase 8.
            $table->unsignedInteger('current_version')->default(1);

            $table->timestamps();
            $table->softDeletes();

            $table->index(['lockbox_id', 'sort_order']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('secrets');
        Schema::dropIfExists('lockboxes');
        Schema::dropIfExists('vault_memberships');
        Schema::dropIfExists('vaults');
    }
};
